
name: MINIAPP_ISSUE_LABEL_SCHEDULER
description: xhs miniapp github task scheduler action

author: tailiang
branding:
  color: blue
  icon: package
inputs:
  wx-robot-hook:
    description: "wechat robot token"
    required: true

  tapd-new-task:
    description: "xhs tapd new task url"
    required: true

  tapd-workspace-token:
    description: "xhs tapd workspace token"
    required: true

  github-token:
    description: "github token"
    required: true

  close-issue-label:
    description: "close issue label"
    required: false
  
  close-issue-comment:
    description: "close issue comment"
    required: true

runs:
  using: node16
  main: ./main.js