name: XHS_MINIAPP_ISSUE_SCHEDULER
on:
  issues:
    types: [opened]
jobs:
  miniapp-issue-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm -v
      - run: node -v
      - run: npm i superagent minimist @actions/github @actions/core chalk@4.x
      - name: miniapp-issue-schduler
        uses: ./scripts/actions/scheduler/
        with:
          wxRobotHook: ${{ secrets.__wx_robot_hook__ }}
          tapdNewTask: ${{ secrets.__tapd_new_task__ }}
          tapdWorkspaceToken: ${{ secrets.__tapd_workspace_token__ }}