name: XHS_MINIAPP_ISSUE_SCHEDULER
on:
  issues:
    types: [opened]
jobs:
  miniapp-issue-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm -v
      - run: node -v
      - run: npm i superagent minimist @actions/github @actions/core chalk@4.x
      - name: miniapp-issue-schduler
        uses: ./scripts/actions/scheduler/
        with:
          wx-robot-hook: ${{ secrets.__wx_robot_hook__ }}
          tapd-new-task: ${{ secrets.__tapd_new_task__ }}
          tapd-workspace-token: ${{ secrets.__tapd_workspace_token__ }}
          pingcode-mini-url-auth: ${{ secrets.__pingcode_mini_url_auth__ }}
          pingcode-mini-url-issue: ${{ secrets.__pingcode_mini_url_issue__ }}
          pingcode-mini-client-id: ${{ secrets.__pingcode_client_id__ }}
          pingcode-mini-secret: ${{ secrets.__pingcode_mini_secret__ }}
          pingcode-mini-project-id: ${{ secrets.__pingcode_mini_project_id__ }}
          feedback-mini-url-create: ${{ secrets.__feedback_mini_uri_create__ }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue-label: "close"
          close-issue-comment: "当前的 issue 填写不正确，请参考模板中的必填信息(问题分类、服务商等)。\n\n我们将关闭这个问题，请使用剪贴板中的内容创建一个新的问题。\n\n祝您使用愉快！"