name: XHS_MINIAPP_ISSUE_COMMENT
on:
  issues:
    types:
      - opened
jobs:
  xhs-issue-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: miniapp-issue-comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            您好开发者, 我们已收到你的问题, 已通知开发团队进行处理！
            如您未阅读我们的开发文档，可先参阅开发文档 [小红书问题处置流程](https://miniapp.xiaohongshu.com/docs/guide/exceptionPerformanceWhiteScreen) 
            :sparkles: 感谢您的提问！:sparkles:
          reactions: heart, hooray, laugh
