name: XHS_MINIAPP_ISSUE_LABEL
on:
  issues:
    types:
      - opened
jobs:
  xhs-issue-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm -v
      - run: node -v
      - run: npm i superagent minimist @actions/github @actions/core chalk@4.x
      - run: ls
      - name: miniapp-issue-label
        uses: ./scripts/actions/label/
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-labeled: false
